---
# tasks file for provision

# Installs Python3, if it doesn't exist. raw_text variable is defined in group_vars/all.yml
# and tests for various package managers
- name: Install Python3
  raw: "{{ raw_text }}"
  ignore_errors: yes
  no_log: true

# Runs Setup module to gather new facts, since Python3 is now installed
- name: Gather facts about hosts after Python3 install
  setup:

# Creates the managed host's ansible user, whatever is specified in vars/main.yml
- name: Create the "{{ ansible_user }}" user
  user: 
    name: "{{ ansible_user }}"
    state: present

# Adds SSH public keys for the ansible user created in the previous step
- name: Add SSH public keys to "{{ ansible_user }}" user
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ vars.pubkeys }}"

# Creates sudo configuration for the ansible user
- name: Sudo configuration for "{{ ansible_user }}"
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ ansible_user }}
    validate: 'visudo -cf %s'
    mode: 0440
