---
########################################
## Unattended Upgrades / Security Play##
########################################
- name: Unattended Upgradess + Security hardening
  hosts: raw
  roles:
  - smtp-setup
  - unattended-upgrades
  - linux-security
  tasks:

# Set time to current timezone - ntp server is not required
    - name: Set timezone to {{ vars.time_zone }}
      community.general.timezone:
        name: "{{ vars.time_zone }}"

  vars_files:
    - ./vars/vars.yml


#######################
## Jamulus setup Play##
#######################
- name: Set up Jamulus
  hosts: raw
  roles:
  - jamulus-setup



