---
# tasks file for linux-security
# Makes sure firewalld is installed
- name: firewalld installation check
  apt:
    name: firewalld
    state: present
  notify: start firewalld

# This will group hosts by specific key (group_vars) using OS Distribution ansible facts
# This will FAIL if there is no python interpreter installed (solved in previous step)
# - name: Group by OS
#   group_by:
#     key: os_{{ ansible_facts['distribution'] }}

# Modifies sshd config, mostly to disable password auth & disable root login
# Notifies handler in handlers/main.yml to restart sshd after sshd config modificaiton
- name: SSHD configuration, disable root login / password auth 
  template:
    src: sshd_config_conf.j2
    dest: /etc/ssh/sshd_config.d/10-linux-security.conf
    validate: 'sshd -t -f %s'
    mode: 0640
  notify: restart sshd

# Remove Small diffie-hellman moduli, as per: https://www.ssh-audit.com/hardening_guides.html#ubuntu_20_04_lts
# To be done later

# Notify via mail on SSH login 
# - upload .sh file
# - add line to /etc/pam.d/sshd
- name: Upload shell script for SSH login notification
  template:
    src: ssh_notify.j2
    dest: /etc/ssh/login_notify.sh
    owner: root
    group: root
    mode: 0700

# WARNING, this is very spammy in case you're ssh'ing into the host often! Should be a conditional / variable
# Make this optional/conditional
# - name: Modify sshd PAM file to trigger SSH login notification script
#   lineinfile:
#     regexp: "^(#)?session optional pam_exec.so seteuid /etc/ssh/login_notify.sh"
#     line: "session optional pam_exec.so seteuid /etc/ssh/login_notify.sh"
#     state: present
#     dest: /etc/pam.d/sshd
#   notify:
#   - restart sshd

- name: Firewalld set SSH port {{ vars.ssh_port }} with rate limiting
  firewalld:
    rich_rule: "rule family='ipv4' port port='{{ vars.ssh_port }}' protocol='tcp' accept limit value='5/m'"
    permanent: yes
    immediate: yes
    state: enabled
    
# Maybe instead of having this option, the previous one should upload a .j2 template with ssh service modified
- name: Ensure default ssh service is disabled
  firewalld:
    service: ssh
    permanent: yes
    immediate: yes
    state: disabled