---
# tasks file for linux-security
# Notify via mail on SSH login 
# - upload .sh file
# - add line to /etc/pam.d/sshd
- name: Upload shell script for SSH login notification
  template:
    src: ssh_notify.j2
    dest: /etc/ssh/login_notify.sh
    owner: root
    group: root
    mode: 0700

# Warning, spammy in case you're logging into the box often!
# Make this optional/conditional
# - name: Modify sshd PAM file to trigger SSH login notification script
#   lineinfile:
#     regexp: "^(#)?session optional pam_exec.so seteuid /etc/ssh/login_notify.sh"
#     line: "session optional pam_exec.so seteuid /etc/ssh/login_notify.sh"
#     state: present
#     dest: /etc/pam.d/sshd
#   notify:
#   - restart sshd

- name: Firewalld set SSH port {{ vars.ssh_port }} with rate limiting
  firewalld:
    rich_rule: "rule family='ipv4' port port='{{ vars.ssh_port }}' protocol='tcp' accept limit value='5/m'"
    permanent: yes
    immediate: yes
    state: enabled
    
# Maybe instead of having this option, the previous one should upload a .j2 template with ssh service modified
- name: Ensure default ssh service is disabled
  firewalld:
    service: ssh
    permanent: yes
    immediate: yes
    state: disabled

