---
# handlers file for linux-security
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: start firewalld
  service:
    name: firewalld
    enabled: yes
    state: restarted